/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface CalendarMindtric {
    'name': string;
  }
  interface MesCalendar {
    'name': string;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLCalendarMindtricElement extends Components.CalendarMindtric, HTMLStencilElement {}
  var HTMLCalendarMindtricElement: {
    prototype: HTMLCalendarMindtricElement;
    new (): HTMLCalendarMindtricElement;
  };

  interface HTMLMesCalendarElement extends Components.MesCalendar, HTMLStencilElement {}
  var HTMLMesCalendarElement: {
    prototype: HTMLMesCalendarElement;
    new (): HTMLMesCalendarElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'calendar-mindtric': HTMLCalendarMindtricElement;
    'mes-calendar': HTMLMesCalendarElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface CalendarMindtric extends JSXBase.HTMLAttributes<HTMLCalendarMindtricElement> {
    'name'?: string;
  }
  interface MesCalendar extends JSXBase.HTMLAttributes<HTMLMesCalendarElement> {
    'name'?: string;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'calendar-mindtric': CalendarMindtric;
    'mes-calendar': MesCalendar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


